-- startklar.tools – Grundschema
-- Der Runner faehrt diese Datei bereits in einer Transaktion, deshalb kein
-- eigenes BEGIN/COMMIT hier.

-- Trigger-Funktion: haelt updated_at aktuell
CREATE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- ── Kategorien ────────────────────────────────────────────────────────────
-- Eine Taxonomie fuer Themen und Tool-Kategorien. parent_id verweist auf die
-- eigene Tabelle, damit Unterkategorien moeglich sind.
CREATE TABLE categories (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug       TEXT NOT NULL UNIQUE,
  name       TEXT NOT NULL,
  parent_id  INTEGER REFERENCES categories(id) ON DELETE SET NULL,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX categories_parent_id_idx ON categories(parent_id);


-- ── Artikel ───────────────────────────────────────────────────────────────
CREATE TABLE articles (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug             TEXT NOT NULL UNIQUE,
  title            TEXT NOT NULL,
  excerpt          TEXT NOT NULL DEFAULT '',
  content_md       TEXT NOT NULL DEFAULT '',
  category_id      INTEGER REFERENCES categories(id) ON DELETE SET NULL,
  status           TEXT NOT NULL DEFAULT 'entwurf'
                     CHECK (status IN ('entwurf', 'veroeffentlicht')),
  meta_title       TEXT NOT NULL DEFAULT '',
  meta_description TEXT NOT NULL DEFAULT '',
  published_at     TIMESTAMPTZ,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX articles_category_id_idx ON articles(category_id);
CREATE INDEX articles_status_published_at_idx
  ON articles(status, published_at DESC);
CREATE TRIGGER articles_set_updated_at
  BEFORE UPDATE ON articles
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ── Tools ─────────────────────────────────────────────────────────────────
-- short_code ist der Slug fuer die Weiterleitung  /go/<short_code>.
-- affiliate_url ist das echte Ziel (Quelle der Wahrheit, kein Fremdsystem).
CREATE TABLE tools (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug              TEXT NOT NULL UNIQUE,
  name              TEXT NOT NULL,
  short_description TEXT NOT NULL DEFAULT '',
  affiliate_url     TEXT NOT NULL,
  short_code        TEXT NOT NULL UNIQUE,
  category_id       INTEGER REFERENCES categories(id) ON DELETE SET NULL,
  status            TEXT NOT NULL DEFAULT 'entwurf'
                      CHECK (status IN ('entwurf', 'veroeffentlicht')),
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX tools_category_id_idx ON tools(category_id);
CREATE TRIGGER tools_set_updated_at
  BEFORE UPDATE ON tools
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ── Artikel ↔ Tools ──────────────────────────────────────────────────────
-- Rein redaktionell: welche Tools in welchem Artikel verlinkt sind.
CREATE TABLE article_tools (
  article_id INTEGER NOT NULL REFERENCES articles(id) ON DELETE CASCADE,
  tool_id    INTEGER NOT NULL REFERENCES tools(id) ON DELETE CASCADE,
  sort_order INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (article_id, tool_id)
);
CREATE INDEX article_tools_tool_id_idx ON article_tools(tool_id);


-- ── Klicks ────────────────────────────────────────────────────────────────
-- Eine Zeile pro Klick auf  /go/<short_code>.
-- article_id kommt aus  ?a=<slug>  am Link, sonst aus dem Referer, sonst NULL
-- (Klick ausserhalb eines Artikels, z.B. aus dem Tool-Verzeichnis).
-- ip_hash ist ein taeglich wechselnder Hash, keine Klar-IP (DSGVO).
CREATE TABLE clicks (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tool_id    INTEGER NOT NULL REFERENCES tools(id) ON DELETE CASCADE,
  article_id INTEGER REFERENCES articles(id) ON DELETE SET NULL,
  clicked_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  referrer   TEXT NOT NULL DEFAULT '',
  user_agent TEXT NOT NULL DEFAULT '',
  ip_hash    TEXT NOT NULL DEFAULT '',
  is_bot     BOOLEAN NOT NULL DEFAULT false
);
CREATE INDEX clicks_tool_id_clicked_at_idx ON clicks(tool_id, clicked_at DESC);
CREATE INDEX clicks_article_id_clicked_at_idx
  ON clicks(article_id, clicked_at DESC);


-- ── Admin ─────────────────────────────────────────────────────────────────
-- Ein Nutzer reicht. session_version wird bei Passwortwechsel hochgezaehlt,
-- damit alte Sitzungen ungueltig werden.
CREATE TABLE admin_users (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email           TEXT NOT NULL UNIQUE,
  password_hash   TEXT NOT NULL,
  session_version INTEGER NOT NULL DEFAULT 0,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
