-- Newsletter mit Double-Opt-in. Eine Adresse gilt erst als Empfaenger, wenn
-- confirmed_at gesetzt ist. token ist der Bestaetigungsschluessel aus der Mail.

CREATE TABLE newsletter_subscribers (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email        TEXT NOT NULL UNIQUE,
  token        TEXT NOT NULL,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  confirmed_at TIMESTAMPTZ,
  unsubscribed_at TIMESTAMPTZ
);
CREATE INDEX newsletter_subscribers_token_idx ON newsletter_subscribers(token);
