-- Versand-Teil des Newsletters. Kein externer Dienst, alles über das eigene
-- SMTP-Postfach.

-- Nachweis, welche Ausgabe wann an wie viele Empfänger ging. Verhindert auch
-- Verwirrung über versehentlichen Doppelversand.
CREATE TABLE newsletter_campaigns (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  betreff        TEXT NOT NULL,
  inhalt_md      TEXT NOT NULL,
  empfaenger     INTEGER NOT NULL DEFAULT 0,
  fehlgeschlagen INTEGER NOT NULL DEFAULT 0,
  gesendet_am    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Drosselung der Bestätigungsmail: pro Adresse höchstens alle 10 Minuten eine.
-- Ohne das kann man über das Anmeldeformular eine fremde Adresse mit
-- Bestätigungsmails zumüllen.
ALTER TABLE newsletter_subscribers ADD COLUMN last_mail_at TIMESTAMPTZ;
